language: node_js
dist: trusty
os: linux
group: stable
compiler: g++
addons:
  apt:
    packages:
      - libxi-dev
node_js:
  - 6.9.1
  - 7
script:
  - npm run lint
  - npm run fast-test
after_success:
  - cat coverage/lcov.info | coveralls
